name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Branch to trigger on push
  pull_request:
    branches:
      - main  # Branch to trigger on pull request

jobs:
  build:
    runs-on: ubuntu-latest  # Operating system environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout the repository

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Action to set up Node.js
        with:
          node-version: '14'

      # Backend
      - name: Install backend dependencies
        run: npm install
        working-directory: backend  # Path relative to the root of the repository

      - name: Start backend
        run: npm run dev
        working-directory: backend  # Path relative to the root of the repository

      # Frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend  # Path relative to the root of the repository

      - name: Build frontend application
        run: npm run build
        working-directory: frontend  # Path relative to the root of the repository

      # Optionally, you can run frontend tests if needed
      #- name: Run frontend tests
      #  run: npm test
      #  working-directory: frontend  # Path relative to the root of the repository
