# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  # Operating system environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Node.js
        uses: actions/setup-node@v2  

      - name: Install dependencies
        run: |
          cd backend
          npm install 


     

      - name: Build Frontend
        run: |
          cd backend
          npm run dev

      - name: Build Backend
        run: |
          cd frontend
          npm start


      # - name: Package artifact
      #   run: zip -r app.zip ./dist  # Example command to package the artifact

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: my-app-artifact
      #     path: app.zip  # Path to the artifact to upload
